---
- name: Configure Jenkins
  hosts: ci
  become: yes

  vars:
    java_packages:
      - openjdk-8-jdk

    solita_jenkins_plugins:
      - git
      - copyartifact
      - build-pipeline-plugin
      - delivery-pipeline-plugin
      - build-name-setter
      - cloudbees-folder
      - timestamper
      - ws-cleanup
      - ansicolor

    solita_ansible_version: 2.1.0.0

  pre_tasks:
    - name: Add OpenJDK PPA (for Java 8)
      apt_repository: repo="ppa:openjdk-r/ppa"

  roles:
    - name: solita.jenkins
      tags: jenkins

    - name: solita.ansible
      tags: ansible

  tasks:
    - name: Configure Git for Jenkins
      git_config:
        scope: global
        name: "{{ item.k }}"
        value: "{{ item.v }}"
      with_items:
        - { k: user.name, v: Jenkins }
        - { k: user.email, v: jenkins@example.com }

    - name: Install Maven
      apt: name=maven state=installed

    - name: Generate SSH key for Jenkins
      user: name=jenkins generate_ssh_key=yes

    - name: Fetch Jenkins' public key
      fetch:
        src: /var/lib/jenkins/.ssh/id_rsa.pub
        dest: "{{ inventory_dir }}/../jenkins_id_rsa.pub"
        flat: yes

- name: Give Jenkins sudo access
  hosts: ci_sudo_access
  become: yes

  tasks:
    - name: Create user jenkins
      user:
        name: jenkins

    - name: Give jenkins sudo permissions
      copy:
        dest: /etc/sudoers.d/jenkins
        content: "jenkins ALL = (ALL:ALL) NOPASSWD: ALL"
        validate: visudo -cf %s

    - name: Allow Jenkins to log in as jenkins
      authorized_key: "user=jenkins key='{{ item }}'"
      with_file:
        - "{{ inventory_dir }}/../jenkins_id_rsa.pub"
