---
- hosts: app
  serial: 1
  become: yes

  tasks:
    - include_vars: app_vars.yml

    - name: Copy application files to server
      copy:
        src: "{{ item['file'] }}"
        dest: "{{ app_dir }}/{{ item['file'] }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "{{ item['mode'] }}"
      with_items:
        - {file: "{{ app_jar }}", mode: ug=rw,o=r}
        - {file: start, mode: ug=rwx,o=r}
        - {file: stop, mode: ug=rwx,o=r}

    - name: Stop the application
      command: "sudo -u {{ app_user }} {{ app_dir }}/stop"
      args:
        removes: "{{ app_pid }}"

    - name: Start the application
      command: "sudo -u {{ app_user }} {{ app_dir }}/start"
      args:
        creates: "{{ app_pid }}"
