#!/bin/bash
set -eu
cd "$(dirname $BASH_SOURCE)"

echo 'Updating inventory...'
echo '###############################################################################' > inventory
echo '#                                                                             #' >> inventory
echo '# DO NOT EDIT THIS FILE!                                                      #' >> inventory
echo '#                                                                             #' >> inventory
echo '# Make your changes to:                                                       #' >> inventory
echo '#                                                                             #' >> inventory
echo '#     playground/inventory.template                                           #' >> inventory
echo '#                                                                             #' >> inventory
echo '# Then run:                                                                   #' >> inventory
echo '#                                                                             #' >> inventory
echo '#     playground/update-inventory.sh                                          #' >> inventory
echo '#                                                                             #' >> inventory
echo '###############################################################################' >> inventory
echo >> inventory
for h in $(ls ../docker/playground-hosts); do
  echo "$h ansible_user=root ansible_host=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $h) ansible_ssh_extra_args=\"-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no\"" >> inventory
done
echo >> inventory
cat inventory.template >> inventory
