#!/bin/bash
set -eu
cd "$(dirname $BASH_SOURCE)"
source .util/docker.sh

container_ip="$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $1)"
ssh \
  -o UserKnownHostsFile=/dev/null \
  -o StrictHostKeyChecking=no \
  -o LogLevel=quiet \
  -t \
  -A \
  root@$container_ip
