#!/bin/bash
set -eu
cd "$(dirname $BASH_SOURCE)"

../../docker/PROJECT-ansible/start.sh

docker_host="$(../../docker/host)"
ansible_ssh_port="$(../../docker/port PROJECT-ansible 22 | sed -e 's/.\+://')"
ssh \
  -o UserKnownHostsFile=/dev/null \
  -o StrictHostKeyChecking=no \
  -o LogLevel=ERROR \
  -t \
  -A \
  "ansible@$docker_host" \
  -p "$ansible_ssh_port" \
  "cd /project && $@" \
  2>&1 | grep -vF "Connection to $docker_host closed."
