#!/bin/bash
set -eu
cd "$(dirname $BASH_SOURCE)"

ssh-add -L >/dev/null 2>&1 || {
  ssh_add_status="$?"
  echo 'This command needs access to your SSH keys.' >&2
  echo >&2
  if [[ $ssh_add_status -eq 2 ]]; then
    echo 'Please run the following command to start ssh-agent:' >&2
    echo >&2
    echo '    ssh-agent bash' >&2
    echo >&2
    echo 'Then add your keys to the agent:' >&2
    echo >&2
    echo '    ssh-add' >&2
    echo >&2
    exit 1
  elif [[ $ssh_add_status -eq 1 ]]; then
    echo 'Please run the following command to add your SSH keys to ssh-agent:' >&2
    echo >&2
    echo '    ssh-add' >&2
    echo >&2
    exit 1
  fi
}

../../docker/PROJECT-ansible/start.sh

docker_host="$(../../docker/host)"
ansible_ssh_port="$(../../docker/port PROJECT-ansible 22 | sed -e 's/.\+://')"
ssh \
  -o UserKnownHostsFile=/dev/null \
  -o StrictHostKeyChecking=no \
  -o LogLevel=ERROR \
  -t \
  -A \
  "ansible@$docker_host" \
  -p "$ansible_ssh_port" \
  "cd /project && $@" \
  2>&1 | grep -vF "Connection to $docker_host closed."
